import '@hsmos-ui/components/base/style/css'
import '@hsmos-ui/theme-chalk/el-table.css'
import '@hsmos-ui/components/checkbox/style/css'
import '@hsmos-ui/components/tag/style/css'
import '@hsmos-ui/components/tooltip/style/css'
import '@hsmos-ui/components/scrollbar/style/css'
