import '@hsmos-ui/components/base/style'
import '@hsmos-ui/theme-chalk/src/table.scss'
import '@hsmos-ui/components/checkbox/style'
import '@hsmos-ui/components/tag/style'
import '@hsmos-ui/components/tooltip/style'
import '@hsmos-ui/components/scrollbar/style'
